apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  labels: 
    app: {{.Values.name}}
spec:
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{.Values.name}}:8.0
        envFrom:
        - configMapRef:
            name: {{.Values.name}}
        ports:
        - containerPort: 3306
          name: {{.Values.name}}
        # readinessProbe:
        #   exec:
        #     command:
        #     - "bash" 
        #     - "-c"
        #     - "mysql --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --execute=\"SELECT 1;\""
        #   initialDelaySeconds: 20
        livenessProbe:
          exec:
            command:
            - "bash" 
            - "-c"
            - "mysql --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --execute=\"SELECT 1;\""
          initialDelaySeconds: 10
          periodSeconds: 15
        volumeMounts:
        - name: {{.Values.name}}-storage
          mountPath: /var/lib/{{.Values.name}}
          subPath: {{.Values.name}}
      volumes:
      - name: {{.Values.name}}-storage
        persistentVolumeClaim:
          claimName: pvc-{{.Values.name}}
