apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name}}
  labels:
    app: {{ .Values.name}}
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.ports.port}}
    targetPort: {{ .Values.ports.port}}
  selector:
    app: {{ .Values.name}}
  type: NodePort