- name: create cluster
  shell: |
    export GOOGLE_APPLICATION_CREDENTIALS="{{ playbook_dir }}/plan/auth/serviceaccount.json" }}
    cd {{ playbook_dir }}/plan;
    terraform workspace new {{ env }}
    terraform workspace select {{ env }}
    terraform plan -var-file=env.tfvars;
    terraform apply -var-file=env.tfvars -auto-approve -refresh=true;
  when: (operation == "create")