- name: destroy cluster
  shell: |
    export GOOGLE_APPLICATION_CREDENTIALS={{ playbook_dir }}/plan/auth/serviceaccount.json
    cd {{ playbook_dir }}/plan;
    terraform workspace select {{ env }}
    terraform destroy -var-file=env.tfvars -auto-approve
  when: (operation == "destroy")