apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotes-api
  template:
    metadata:
      labels:
        app: quotes-api
    spec:
      initContainers:
        - name: check-mysql
          image: busybox:1.31.1
          command: ['sh', '-c', 'until nslookup data.default.svc.cluster.local; do echo waiting for mysql; sleep 2; done;']
      containers:
      - name: quotes-api
        image: marjugoncalves/quotesapi:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
          name: quotes-api
        envFrom:
          - configMapRef:
              name: backend
# add health check and HPA