apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 300Mi
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: "/home/docker"
  persistentVolumeReclaimPolicy: Retain