apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: quotes-virtual-service
  # namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - quotes-gateway
  http:
  - route:
    - destination:
        host: quotes-api
        subset: v1
      weight: 90
    - destination:
        host: quotes-api
        subset: v2
      weight: 10