apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: quotes-virtual-service
spec:
  hosts:
  - "*"
  gateways:
  - default/quotes-gateway
  http:
  - route:
    - destination:
        host: quotes-api.quotes-system.svc.cluster.local