apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.service.name }}
  ports:
  - name: {{ .Values.service.name }} 
    port: {{ .Values.service.ports.port }}
    targetPort: {{ .Values.service.ports.containerPort }}
  clusterIP: None

