apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: quotes-api-v2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quotes-api-v2
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
